const ROLES = Object.freeze({
  ADMIN: "ADMIN",

  // Operations
  OPERATIONS: "OPERATIONS",
  FIELD_SUPERVISOR: "FIELD_SUPERVISOR",
  GENERAL_SUPERVISOR: "GENERAL_SUPERVISOR",
  DISPATCHER: "DISPATCHER",

  // Management
  DEPT_MANAGER: "DEPT_MANAGER",
  GENERAL_MANAGER: "GENERAL_MANAGER",
  GENERAL_RESPONSIBLE: "GENERAL_RESPONSIBLE",
  CONTRACT_MANAGER: "CONTRACT_MANAGER",
  MAINTENANCE_MANAGER: "MAINTENANCE_MANAGER",

  // Finance / HR
  HR: "HR",
  ACCOUNTANT: "ACCOUNTANT",

  // Store
  STOREKEEPER: "STOREKEEPER",
});

module.exports = { ROLES };