// src/auth/roles.js

const ROLES = Object.freeze({
  ADMIN: "ADMIN",

  // Operations
  FIELD_SUPERVISOR: "FIELD_SUPERVISOR",
  GENERAL_SUPERVISOR: "GENERAL_SUPERVISOR",

  // Management
  DEPT_MANAGER: "DEPT_MANAGER",
  GENERAL_MANAGER: "GENERAL_MANAGER",
  GENERAL_RESPONSIBLE: "GENERAL_RESPONSIBLE",
  CONTRACT_MANAGER: "CONTRACT_MANAGER",

  // Store
  STOREKEEPER: "STOREKEEPER",

  // Existing
  HR: "HR",
  ACCOUNTANT: "ACCOUNTANT",
  DISPATCHER: "DISPATCHER",
});

module.exports = { ROLES };