const ROLES = {
  ADMIN: "ADMIN",
  ACCOUNTANT: "ACCOUNTANT",
  FIELD_SUPERVISOR: "FIELD_SUPERVISOR",
  GENERAL_SUPERVISOR: "GENERAL_SUPERVISOR",
  DEPT_MANAGER: "DEPT_MANAGER",
  GENERAL_MANAGER: "GENERAL_MANAGER",
  GENERAL_RESPONSIBLE: "GENERAL_RESPONSIBLE",
  CONTRACT_MANAGER: "CONTRACT_MANAGER",
  STOREKEEPER: "STOREKEEPER",
  HR: "HR",
  DISPATCHER: "DISPATCHER",
  OPERATIONS: "OPERATIONS",
  MAINTENANCE_MANAGER: "MAINTENANCE_MANAGER",
};

const PLATFORM_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  USER: "USER",
};

module.exports = {
  ROLES,
  PLATFORM_ROLES,
};